FROM node:18-alpine

RUN apk add --no-cache ca-certificates

WORKDIR /srv
RUN npm i -g @soketi/soketi

# Cloud Run sets PORT env var
ENV PORT=8080
EXPOSE 8080

# Soketi will read these from environment:
# PORT, SOKETI_DEBUG, SOKETI_DEFAULT_APP_ID, SOKETI_DEFAULT_APP_KEY, 
# SOKETI_DEFAULT_APP_SECRET, SOKETI_ADAPTER_DRIVER, SOKETI_ADAPTER_REDIS_*

CMD soketi start --host=0.0.0.0 --port=$PORT
